// vue-application/src/components/GreenBeans.vue
<template>
  <header class="hello">
    <img alt="Damon Gant" src="../assets/damon.gif">
    <h1>I only eat <span class="green-strings">{{ food }}</span> for breakfast!</h1>
  </header>
</template>

<script>
export default {
  name: "green beans",
  props: {
    food: String
  }
}
</script>

<style scoped>
.green-strings {
  color: green;
}
</style>

// react-application/src/components/GreenBeans.js
import damon from "../assets/damon.gif";
import "./GreenBeans.css";

function GreenBeans() {
  const food = "green beans";
  return (
    <div className="App">
      <header className="App-header">
        <img src={damon} alt="Damon Gant" />
        <h1>I only eat <span className="green-strings">{food}</span> for breakfast!</h1>
      </header>
    </div>
  );
}

export default GreenBeans;
