// vue-application/src/views/Folders.vue
<template>
  <router-link :to="{ name: 'Home' }">Back to home page</router-link>
  <h2>Folders</h2>
  <SearchBar @updateSearch="updateSearch" />
  <!-- Display the folders -->
  <ul v-if="folders">
    <li v-for="folder in selectedFolders" :key="folder.id">
      <router-link :to="{ name: 'Folder', params: { id: folder.id } }">{{ folder.name }}</router-link>
    </li>
  </ul>
  <p v-else>Loading folders...</p>
</template>

<script>
import SearchBar from "../components/SearchBar.vue"

export default {
  name: "Folders",
  components: {
    SearchBar
  },
  data() {
    return {
      folders: null,
      selectedFolders: null
    }
  },
  methods: {
    updateSearch(searchTerms) {
      this.selectedFolders = this.folders.filter((folder) => folder.name.toLowerCase().includes(searchTerms.toLowerCase()))
    }
  },
  mounted() {
    // Ideally, this would contain an API fetch
    // But for now, we'll set the folders manually
    this.folders = [
      { id: 0, name: "Ace Attorney", files: ["damon.gif", "notguilty.jpg", "apolloobjection.wav"] },
      { id: 1, name: "The Silver Case", files: ["spinninginachair.mp4", "glgiscoming.jpg", "glgishere.jpg", "ohthatsphoenixwright.jpg"] },
      { id: 2, name: "Gallant Geese", files: ["goose1.jpg", "goose2.jpg", "goose3.jpg"] },
      { id: 3, name: "My Favorites", files: ["damon.gif", "spinninginachair.mp4", "goose2.jpg"] }
    ]
    this.selectedFolders = this.folders
  }
}
</script>

<style scoped>
</style>

// react-application/src/views/Folders.js
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import SearchBar from "../components/SearchBar";

function Folders() {
  const [folders, setFolders] = useState(null);
  const [selectedFolders, setSelectedFolders] = useState(null);

  const updateSearch = (searchTerms) => {
    setSelectedFolders(folders.filter((folder) => folder.name.toLowerCase().includes(searchTerms.toLowerCase())));
  }

  useEffect(() => {
    // Ideally, this would contain an API fetch
    // But for now, we'll set the folders manually
    const folders = [
      { id: 0, name: "Ace Attorney", files: ["damon.gif", "notguilty.jpg", "apolloobjection.wav"] },
      { id: 1, name: "The Silver Case", files: ["spinninginachair.mp4", "glgiscoming.jpg", "glgishere.jpg", "ohthatsphoenixwright.jpg"] },
      { id: 2, name: "Gallant Geese", files: ["goose1.jpg", "goose2.jpg", "goose3.jpg"] },
      { id: 3, name: "My Favorites", files: ["damon.gif", "spinninginachair.mp4", "goose2.jpg"] }
    ];
    setFolders(folders);
    setSelectedFolders(folders);
  }, []);

  return (
    <div>
      <Link to="/">Back to home page</Link>
      <h2>Folders</h2>
      <SearchBar updateSearch={(searchTerms) => updateSearch(searchTerms)} />
      <ul>
        {selectedFolders && selectedFolders.map((folder) => (
        <li key={folder.id}>
          <Link to={"/folders/" + folder.id}>{folder.name}</Link>
        </li>
        ))}
      </ul>
      { !selectedFolders && (
      <p>Loading folders...</p>
      )}
    </div>
  );
}

export default Folders;
